policratus/pupyl

.coveragerc
.github/workflows/pupyl-ci.yml
README.md

* Adding a coverage badge (provided by [codecov.io](https://codecov.io/))

✅ Adding coverage badge

---

setup.py

* Updating based on `pypi` classifiers.

📦 Fixing packaging publication issues.

---

pupyl/duplex/file_io.py
tests/test_file_io.py
version

* Found a bug which avoided reading online compressed files with `scan()` method.
* Updating version updater.

🐛 Fixing a bug on online reading compressed files.

---

.github/workflows/python-package-conda.yml
conda/meta.yaml
version

* Updating version updater to be compliant with `anaconda` packages;
* Creating action for `anaconda` publishing.

📦 Creating package publishing to anaconda.org

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

* Creating a code of conduct for `pupyl`;
* Guidelines for contributors.

📝 Community guidelines

---

.github/workflows/codeql-analysis.yml
.github/workflows/pupyl-ci.yml
setup.py

* Changing `codeql` action to not perform dependencies auto-installation.
* Updating `python` default supported version to 3.8

🔒 Updating code analysis and dependencies versions

---

pupyl/duplex/file_io.py
pupyl/search.py

**Resolves** #57.
* Fixing issues related to path resolution on Windows systems;

🐛 Fixing windows path resolution

---

conda/meta.yaml
pupyl/search.py
setup.py

* Updating to version `0.10.5`

🔖 [skip-ci] Updating to version 0.10.5

---

tests/test_features.py

* Rolling back the `facets` test that made coverage down for not testing all possible feature characteristics.

✅ Fixing coverage completeness over facets module

---

pupyl/duplex/file_io.py
pupyl/search.py
pupyl/storage/database.py

* Fixing the progress bar printings that wasn't clearing the previous output

💄 Fixing progress bars

---

conda/meta.yaml
pupyl/search.py
setup.py

* Updating dependencies due to security warnings.

🔖 [skip-ci] Updating to version 0.11.1

---

pupyl/embeddings/features.py
pupyl/search.py

* Letting users know how much of the image scanning processing is done;
* Faster index process on extreme mode

⚡️ Faster indexing and other improvements

---

pupyl/storage/database.py
pupyl/web/interface.py
tests/test_database.py
tests/test_database/0/0.json
tests/test_pupyl.py

**Resolves** #104 
* Adding more information to the metadata of each image, like the internal path;
* Adding more metadata on the web interface.

💄 More metadata information for images

---

TROUBLESHOOTING.md

* Adding installation troubleshooting for macOS users.

📝 Updating TROUBLESHOOTING.md

---

pupyl/duplex/image.py
pupyl/storage/database.py
tests/test_image.py

This is an attempt to fix #161.
I think we can iterate over this in order to find the best design.

🐛 Fix jpeg compression issue

---

CONTRIBUTING.md

✏️ Fix typo in CONTRIBUTING.md

---

tests/test_file_io.py

* Fixing unit test which checks for huge download files.

✅ Updating unit tests

---

pupyl/indexer/facets.py
pupyl/search.py
pupyl/storage/database.py
tests/test_database.py
tests/test_facets.py
tests/test_pupyl.py

**Resolves #199**
* Adding an option to return the distances between the query image and matched images, with increasingly distances.

✨ Adding distances to search results

---

.pylintrc
pupyl/duplex/file_io.py
pupyl/indexer/facets.py
setup.py

* Fixing linter warnings
* Updating some dependencies

💚 Fixing CI

---

.github/workflows/pupyl-ci.yml

* Fixing a bug when uploading test code coverage to `codecov`.

💚 Fixing CI regarding code coverage

---

pupyl/duplex/file_io.py
pupyl/indexer/facets.py

* Updating some new linter checks to maintain code quality.

🚨 Updating linter
